server:
    port: 8761
spring:
    application:
        name: naming-service
eureka:
    instance:
        prefer-ip-address: true
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/