server:
    port: 8888
spring:
    application:
        name: spring-cloud-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Enryki/henrique-config-server
                    search-paths: 'greeting-service*'
                    #username: username
                    #password: password
                #default-label: main
    #profiles:
    #    active:
    #        - native