server:
    port: 8080
spring:
    application:
        name: greeting-service
    config:
        import: "optional:configserver:http://localhost:8888/"
    cloud:
        config:
            profile: it
    endpoints:
        web:
            exposure:
                include:
                    - '*'
    endpoint:
        health:
            show-details: ALWAYS
# greeting-service:
#     greeting: "Olá"
#     default-value: "Mundo"
